version: "3.9"

services:
  secret_transferring_service:
    build: .
    ports:
      - 5000:5000
    env_file:
      - local.env
  #   depends_on:
  #     - redis
  # redis:
  #   image: "redis:alpine"
